name: ai-marketing-platform

services:
  backend-build:
    build:
      context: ./backend/platform-api
      dockerfile: Dockerfile
      target: build

  frontend-build:
    build:
      context: ./apps/webapp/spa
      dockerfile: ../Dockerfile
      target: build
