export enum BrandArchetypeName {
	INNOCENT = 'INNOCENT',
	EVERYMAN = 'EVERYMAN',
	HERO = 'HERO',
	OUTLAW = 'OUTLAW',
	EXPLORER = 'EXPLORER',
	CREATOR = 'CREATOR',
	RULER = 'RULER',
	MAGICIAN = 'MAGICIAN',
	LOVER = 'LOVER',
	CAREGIVER = 'CAREGIVER',
	JESTER = 'JESTER',
	SAGE = 'SAGE'
}
