"""add_cascade_delete_to_brand_foreign_keys

Revision ID: d615596d0a5c
Revises: eb82e459abec
Create Date: 2026-01-16 11:48:37.393754

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd615596d0a5c'
down_revision: str | None = 'eb82e459abec'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaign_generation_jobs', 'user_input',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_constraint(op.f('campaign_generation_jobs_brand_id_fkey'), 'campaign_generation_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'campaign_generation_jobs', 'brands', ['brand_id'], ['id'], ondelete='CASCADE')
    op.drop_column('campaign_generation_jobs', 'include_stock_images')
    op.drop_column('campaign_generation_jobs', 'image_urls')
    op.drop_constraint(op.f('campaigns_brand_id_fkey'), 'campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'campaigns', 'brands', ['brand_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.create_foreign_key(op.f('campaigns_brand_id_fkey'), 'campaigns', 'brands', ['brand_id'], ['id'])
    op.add_column('campaign_generation_jobs', sa.Column('image_urls', postgresql.ARRAY(sa.VARCHAR()), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=False))
    op.add_column('campaign_generation_jobs', sa.Column('include_stock_images', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'campaign_generation_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('campaign_generation_jobs_brand_id_fkey'), 'campaign_generation_jobs', 'brands', ['brand_id'], ['id'])
    op.alter_column('campaign_generation_jobs', 'user_input',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###

