"""Update campaign generation jobs inputs

Revision ID: 031c296d87b8
Revises: 4ac2c8cd6657
Create Date: 2025-12-21 18:47:10.642119

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '031c296d87b8'
down_revision: str | None = '4ac2c8cd6657'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaign_generation_jobs', 'user_input',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_column('campaign_generation_jobs', 'include_stock_images')
    op.drop_column('campaign_generation_jobs', 'image_urls')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_generation_jobs', sa.Column('image_urls', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.add_column('campaign_generation_jobs', sa.Column('include_stock_images', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('campaign_generation_jobs', 'user_input',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###

