"""initial schema

Revision ID: 26ded82d4f96
Revises: 
Create Date: 2025-12-01 01:29:20.228041

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '26ded82d4f96'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    conn = op.get_bind()

    postchannel_exists = conn.execute(sa.text(
        "SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'postchannel')"
    )).scalar()

    jobstatus_exists = conn.execute(sa.text(
        "SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'jobstatus')"
    )).scalar()

    if not postchannel_exists:
        sa.Enum('INSTAGRAM', 'LINKEDIN', name='postchannel').create(conn)

    if not jobstatus_exists:
        sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'FAILED', name='jobstatus').create(conn)

    op.create_table('post_generation_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_generation_job_id', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('channel', postgresql.ENUM('INSTAGRAM', 'LINKEDIN', name='postchannel', create_type=False), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'FAILED', name='jobstatus', create_type=False), nullable=False),
    sa.Column('assigned_image_url', sa.String(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_generation_job_id'], ['campaign_generation_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_generation_jobs_campaign_generation_job_id'), 'post_generation_jobs', ['campaign_generation_job_id'], unique=False)

    brand_extraction_exists = conn.execute(sa.text(
        "SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'brand_extraction_jobs')"
    )).scalar()
    if brand_extraction_exists:
        op.drop_table('brand_extraction_jobs')

    campaigns_index_exists = conn.execute(sa.text(
        "SELECT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'campaigns_brand_id_idx')"
    )).scalar()
    if not campaigns_index_exists:
        op.create_index('campaigns_brand_id_idx', 'campaigns', ['brand_id'], unique=False)

    posts_index_exists = conn.execute(sa.text(
        "SELECT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'posts_scheduled_at_idx')"
    )).scalar()
    if not posts_index_exists:
        op.create_index('posts_scheduled_at_idx', 'posts', ['scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('posts_scheduled_at_idx', table_name='posts')
    op.drop_index('campaigns_brand_id_idx', table_name='campaigns')
    op.create_table('brand_extraction_jobs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'FAILED', name='jobstatus'), autoincrement=False, nullable=False),
    sa.Column('website_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('extra_routes', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('brand_extraction_jobs_pkey'))
    )
    op.drop_index(op.f('ix_post_generation_jobs_campaign_generation_job_id'), table_name='post_generation_jobs')
    op.drop_table('post_generation_jobs')
    # ### end Alembic commands ###

