"""campaigns edit

Revision ID: ee2c545616c7
Revises: 163fc10df816
Create Date: 2025-12-07 00:59:11.713853

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ee2c545616c7'
down_revision: str | None = '163fc10df816'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('target_audience', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('content_pillar', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('channels', sa.ARRAY(sa.Enum('INSTAGRAM', 'LINKEDIN', name='postchannel')), nullable=True))
    op.add_column('campaigns', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('campaigns', sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('campaigns', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('campaigns', 'target_audience_description')
    op.drop_column('posts', 'media_description')
    op.drop_column('posts', 'media_user_adjustments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('media_user_adjustments', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('media_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('target_audience_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('campaigns', 'ended_at')
    op.drop_column('campaigns', 'paused_at')
    op.drop_column('campaigns', 'started_at')
    op.drop_column('campaigns', 'channels')
    op.drop_column('campaigns', 'content_pillar')
    op.drop_column('campaigns', 'target_audience')
    # ### end Alembic commands ###

