export enum ContentGenerationJobWorkflowType {
	TEXT_WITH_SINGLE_IMAGE_FROM_USER_MEDIA = 'TEXT_WITH_SINGLE_IMAGE_FROM_USER_MEDIA',
	TEXT_WITH_SINGLE_IMAGE_AI_GENERATED = 'TEXT_WITH_SINGLE_IMAGE_AI_GENERATED',
	TEXT_WITH_SINGLE_IMAGE_PRODUCT_LIFESTYLE = 'TEXT_WITH_SINGLE_IMAGE_PRODUCT_LIFESTYLE'
}
